spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 321321
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

pagehelper: #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

mybatis:
  type-aliases-package: com.xyc.blog.pojo   #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

logging:
  level:
    root: info
    com.xyc.blog: debug
  file:
    name: D:/projects/blog/logs/blog.log
  logback:
    rollingpolicy:
      max-history: 30
